redirects:
  years/latest-changes: https://docs.eqemu.io/server/changelog/server/2021
  years/2020: https://docs.eqemu.io/server/changelog/server/2020
  years/2019: https://docs.eqemu.io/server/changelog/server/2019
  years/2018: https://docs.eqemu.io/server/changelog/server/2018
  years/2017: https://docs.eqemu.io/server/changelog/server/2017
  years/2016: https://docs.eqemu.io/server/changelog/server/2016
  years/2015: https://docs.eqemu.io/server/changelog/server/2015
  years/2014: https://docs.eqemu.io/server/changelog/server/2014
  years/2013: https://docs.eqemu.io/server/changelog/server/2013
  years/2012: https://docs.eqemu.io/server/changelog/server/2012
  years/2011: https://docs.eqemu.io/server/changelog/server/2011
  years/2010: https://docs.eqemu.io/server/changelog/server/2010
  years/2009: https://docs.eqemu.io/server/changelog/server/2009
  years/2008: https://docs.eqemu.io/server/changelog/server/2008
  years/2007: https://docs.eqemu.io/server/changelog/server/2007
  years/2006: https://docs.eqemu.io/server/changelog/server/2006
  years/2005: https://docs.eqemu.io/server/changelog/server/2005
  years/2004: https://docs.eqemu.io/server/changelog/server/2004
  years/2003: https://docs.eqemu.io/server/changelog/server/2003
