redirects:
  changelog/years/latest-changes: https://docs.eqemu.io/server/changelog/server/2021
  changelog/years/2020: https://docs.eqemu.io/server/changelog/server/2020
  changelog/years/2019: https://docs.eqemu.io/server/changelog/server/2019
  changelog/years/2018: https://docs.eqemu.io/server/changelog/server/2018
  changelog/years/2017: https://docs.eqemu.io/server/changelog/server/2017
  changelog/years/2016: https://docs.eqemu.io/server/changelog/server/2016
  changelog/years/2015: https://docs.eqemu.io/server/changelog/server/2015
  changelog/years/2014: https://docs.eqemu.io/server/changelog/server/2014
  changelog/years/2013: https://docs.eqemu.io/server/changelog/server/2013
  changelog/years/2012: https://docs.eqemu.io/server/changelog/server/2012
  changelog/years/2011: https://docs.eqemu.io/server/changelog/server/2011
  changelog/years/2010: https://docs.eqemu.io/server/changelog/server/2010
  changelog/years/2009: https://docs.eqemu.io/server/changelog/server/2009
  changelog/years/2008: https://docs.eqemu.io/server/changelog/server/2008
  changelog/years/2007: https://docs.eqemu.io/server/changelog/server/2007
  changelog/years/2006: https://docs.eqemu.io/server/changelog/server/2006
  changelog/years/2005: https://docs.eqemu.io/server/changelog/server/2005
  changelog/years/2004: https://docs.eqemu.io/server/changelog/server/2004
  changelog/years/2003: https://docs.eqemu.io/server/changelog/server/2003
